pkg-mirror auto
- merge fetch and update into auto
- code cleanup

diff --git a/pkg-mirror b/pkg-mirror
--- a/pkg-mirror
+++ b/pkg-mirror
@@ -1,22 +1,21 @@
 #!/bin/sh
+set -e
 . pkg-mirror.conf
 
-#TODO Makefile DEPENDS
-if ! command -v jq > /dev/null; then
+if ! which jq >/dev/null; then
     echo "jq not found"
     exit 1
 fi
 
-if ! command -v fetch > /dev/null; then
+if ! which fetch >/dev/null; then
     echo "fetch not found"
     exit 1
 fi
 
-#TODO Makefile pre-install
-mkdir -p ${DIR}
+mkdir -p "${DIR}"
 
 log() {
-    echo "$(date) - ${1}" >> ${LOG_FILE}
+    echo "$(date) - ${1}" >>"${LOG_FILE}"
 }
 
 error() {
@@ -24,44 +23,35 @@ error() {
     exit 1
 }
 
-if [ -z "${1}" ]; then
-    echo "Usage: pkg-mirror auto|fetch|update|clean"
-    exit 1
-fi
-
-if [ "${1}" = "clean" ]; then
-    rm -r ${DIR}
+case "${1}" in
+clean)
+    rm -r "${DIR}"
     log "Cleaned directory ${DIR}"
-    exit 0
-fi
-
-if [ "${1}" = "fetch" ]; then
-    mkdir -p ${DIR}/meta
-    mkdir -p ${DIR}/packages/All
-    /usr/bin/fetch "$URL/packagesite.txz" -o "${DIR}/meta" || error "Failed to download packagesite.txz"
-    tar xzf ${DIR}/meta/packagesite.txz -C ${DIR}/meta/ || error "Failed to extract packagesite.txz"
-    cat ${DIR}/meta/packagesite.yaml | jq -r .\|.repopath | sort > ${DIR}/meta/filelist.tmp || error "Failed to generate filelist.tmp"
-    for _file in `cat ${DIR}/meta/filelist.tmp`; do
-        /usr/bin/fetch ${URL}/${_file} -o ${DIR}/packages/All || error "Failed to download ${URL}/${_file}"
+    ;;
+auto)
+    mkdir -p "${DIR}/meta"
+    mkdir -p "${DIR}/packages/All"
+    /usr/bin/fetch "${URL}/packagesite.txz" -o "${DIR}/meta" || error "Failed to download packagesite.txz"
+    tar xzf "${DIR}/meta/packagesite.txz" -C "${DIR}/meta/" || error "Failed to extract packagesite.txz"
+    cat "${DIR}/meta/packagesite.yaml" | jq -r .\|.repopath | sort > "${DIR}/meta/filelist.tmp" || error "Failed to generate filelist.tmp"
+    comm -13 "/usr/local/pkg-mirror/meta/filelist" "${DIR}/meta/filelist.tmp" | while read _file; do
+        /usr/bin/fetch "${URL}/${_file}" -o "${DIR}/packages/All" || error "Failed to download new pkg ${URL}/${_file}"
     done
-    mv ${DIR}/meta/filelist.tmp ${DIR}/meta/filelist || error "Failed to move filelist.tmp"
-    rm ${DIR}/meta/packagesite.yaml* || error "Failed to remove packagesite.yaml"
-    log "Fetched packages to ${DIR}"
-    exit 0
-fi
-
-if [ "${1}" = "update" ]; then
-    comm -13 /usr/local/pkg-mirror/meta/filelist /usr/local/pkg-mirror/meta/filelist.tmp | while read _file; do
-        /usr/bin/fetch ${URL}/${_file} -o ${DIR}/packages/All || error "Failed to download new pkg ${URL}/${_file}"
+    comm -23 "/usr/local/pkg-mirror/meta/filelist" "${DIR}/meta/filelist.tmp" | while read _file; do
+        rm -f "${DIR}/packages/All/${_file}" || error "Failed to delete ${DIR}/packages/All/${_file}"
     done
-    comm -23 /usr/local/pkg-mirror/meta/filelist /usr/local/pkg-mirror/meta/filelist.tmp | while read _file; do
-        rm -f ${DIR}/packages/All/${_file} || error "Failed to delete ${DIR}/packages/All/${_file}"
-    done
-    mv /usr/local/pkg-mirror/meta/filelist.tmp /usr/local/pkg-mirror/meta/filelist || error "Failed to move filelist.tmp"
-    log "Updated packages in ${DIR}"
-    exit 0
-fi
+    mv "${DIR}/meta/filelist.tmp" "/usr/local/pkg-mirror/meta/filelist" || error "Failed to move filelist.tmp"
+    log "Synced packages to ${DIR}"
+    ;;
+help|-h|-help)
+    echo "Usage: pkg-mirror auto|clean"
+    exit 1
+    ;;
+*)
+    echo "Usage: pkg-mirror auto|clean"
+    exit 1
+    ;;
+esac
 
-# Display the help message if the argument is invalid
-echo "Usage: pkg-mirror fetch|update|clean"
-exit 1
+exit 0
+
