Update pkg-mirror

diff --git a/pkg-mirror b/pkg-mirror
--- a/pkg-mirror
+++ b/pkg-mirror
@@ -34,13 +34,13 @@ auto)
     /usr/bin/fetch "${URL}/packagesite.txz" -o "${DIR}/meta" || error "Failed to download packagesite.txz"
     tar xzf "${DIR}/meta/packagesite.txz" -C "${DIR}/meta/" || error "Failed to extract packagesite.txz"
     cat "${DIR}/meta/packagesite.yaml" | jq -r .\|.repopath | sort > "${DIR}/meta/filelist.tmp" || error "Failed to generate filelist.tmp"
-    comm -13 "/usr/local/pkg-mirror/meta/filelist" "${DIR}/meta/filelist.tmp" | while read _file; do
+    comm -13 "${DIR}/meta/filelist" "${DIR}/meta/filelist.tmp" | while read _file; do
         /usr/bin/fetch "${URL}/${_file}" -o "${DIR}/packages/All" || error "Failed to download new pkg ${URL}/${_file}"
     done
-    comm -23 "/usr/local/pkg-mirror/meta/filelist" "${DIR}/meta/filelist.tmp" | while read _file; do
+    comm -23 "${DIR}/meta/filelist" "${DIR}/meta/filelist.tmp" | while read _file; do
         rm -f "${DIR}/packages/All/${_file}" || error "Failed to delete ${DIR}/packages/All/${_file}"
     done
-    mv "${DIR}/meta/filelist.tmp" "/usr/local/pkg-mirror/meta/filelist" || error "Failed to move filelist.tmp"
+    mv "${DIR}/meta/filelist.tmp" "${DIR}/meta/filelist" || error "Failed to move filelist.tmp"
     log "Synced packages to ${DIR}"
     ;;
 help|-h|-help)
